[package]
name = "universal_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
ropey = "1.6.1"
rfd = "0.17.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.42"