[package]
name = "universal_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26" # The GUI Framework
egui = "0.26"   # The Widgets
ropey = "1.6"   # The 1GB+ Text Engine
rfd = "0.14"    # Native File Dialogs
serde = { version = "1.0", features = ["derive"] } # Saving state
chrono = "0.4"